### ISSUE TITLE
Building Mirador Issue

### ISSUE THREAD

**Issue by arthurian** [Harvard-ATG/media_management_lti#108]
I'm running into this issue when I run the **buildMirador** gulp task:

```sh
vagrant@vagrant-ubuntu-trusty-64:~/media_management_lti/app(dev) $ gulp buildMirador
[17:40:54] Using gulpfile /vagrant/app/gulpfile.js
[17:40:54] Starting 'cloneMirador'...
[17:40:54] Finished 'cloneMirador' after 751 μs
[17:40:54] Starting 'buildMirador'...

> phantomjs-prebuilt@2.1.11 install /vagrant/app/tmp/mirador/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs-prebuilt
> node install.js


npm http GET https://registry.npmjs.org/grunt-contrib-jasmine
npm http 304 https://registry.npmjs.org/grunt-contrib-jasmine
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/es5-shim
npm http GET https://registry.npmjs.org/grunt-lib-phantomjs
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/sprintf-js
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/es5-shim
npm http 304 https://registry.npmjs.org/sprintf-js
npm http 304 https://registry.npmjs.org/grunt-lib-phantomjs
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/phantomjs-prebuilt
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/eventemitter2
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/phantomjs-prebuilt
npm http 304 https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/fs.realpath
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/fs.realpath
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/package
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/package
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/es6-promise
npm http 304 https://registry.npmjs.org/es6-promise

module.js:340
    throw err;
          ^
Error: Cannot find module 'throttleit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/app/tmp/mirador/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs-prebuilt/node_modules/request-progress/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 8
npm ERR! not ok code 0

[17:41:01] 'buildMirador' errored after 7.45 s
[17:41:01] Error: Command failed: npm http GET https://registry.npmjs.org/grunt-contrib-jasmine
npm http 304 https://registry.npmjs.org/grunt-contrib-jasmine
npm http GET https://registry.npmjs.org/chalk
npm http GET https://registry.npmjs.org/es5-shim
npm http GET https://registry.npmjs.org/grunt-lib-phantomjs
npm http GET https://registry.npmjs.org/lodash
npm http GET https://registry.npmjs.org/rimraf
npm http GET https://registry.npmjs.org/sprintf-js
npm http 304 https://registry.npmjs.org/rimraf
npm http 304 https://registry.npmjs.org/lodash
npm http 304 https://registry.npmjs.org/chalk
npm http 304 https://registry.npmjs.org/es5-shim
npm http 304 https://registry.npmjs.org/sprintf-js
npm http 304 https://registry.npmjs.org/grunt-lib-phantomjs
npm http GET https://registry.npmjs.org/strip-ansi
npm http GET https://registry.npmjs.org/supports-color
npm http GET https://registry.npmjs.org/ansi-styles
npm http GET https://registry.npmjs.org/escape-string-regexp
npm http GET https://registry.npmjs.org/has-ansi
npm http GET https://registry.npmjs.org/glob
npm http GET https://registry.npmjs.org/eventemitter2
npm http GET https://registry.npmjs.org/phantomjs-prebuilt
npm http GET https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/escape-string-regexp
npm http 304 https://registry.npmjs.org/ansi-styles
npm http 304 https://registry.npmjs.org/has-ansi
npm http 304 https://registry.npmjs.org/supports-color
npm http 304 https://registry.npmjs.org/eventemitter2
npm http 304 https://registry.npmjs.org/strip-ansi
npm http 304 https://registry.npmjs.org/temporary
npm http 304 https://registry.npmjs.org/glob
npm http 304 https://registry.npmjs.org/phantomjs-prebuilt
npm http 304 https://registry.npmjs.org/semver
npm http GET https://registry.npmjs.org/ansi-regex
npm http 304 https://registry.npmjs.org/ansi-regex
npm http GET https://registry.npmjs.org/once
npm http GET https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/path-is-absolute
npm http GET https://registry.npmjs.org/fs.realpath
npm http GET https://registry.npmjs.org/inflight
npm http GET https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/fs.realpath
npm http 304 https://registry.npmjs.org/path-is-absolute
npm http 304 https://registry.npmjs.org/once
npm http 304 https://registry.npmjs.org/minimatch
npm http GET https://registry.npmjs.org/package
npm http 304 https://registry.npmjs.org/inherits
npm http 304 https://registry.npmjs.org/inflight
npm http 304 https://registry.npmjs.org/package
npm http GET https://registry.npmjs.org/wrappy
npm http GET https://registry.npmjs.org/brace-expansion
npm http 304 https://registry.npmjs.org/brace-expansion
npm http GET https://registry.npmjs.org/balanced-match
npm http GET https://registry.npmjs.org/concat-map/0.0.1
npm http 304 https://registry.npmjs.org/wrappy
npm http 304 https://registry.npmjs.org/balanced-match
npm http 304 https://registry.npmjs.org/concat-map/0.0.1
npm http GET https://registry.npmjs.org/es6-promise
npm http 304 https://registry.npmjs.org/es6-promise

module.js:340
    throw err;
          ^
Error: Cannot find module 'throttleit'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/vagrant/app/tmp/mirador/node_modules/grunt-contrib-jasmine/node_modules/grunt-lib-phantomjs/node_modules/phantomjs-prebuilt/node_modules/request-progress/index.js:3:16)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
npm WARN This failure might be due to the use of legacy binary "node"
npm WARN For further explanations, please read
/usr/share/doc/nodejs/README.Debian
 
npm ERR! weird error 8
npm ERR! not ok code 0

    at ChildProcess.exithandler (child_process.js:637:15)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
Running "clean:build" (clean) task
>> 1 path cleaned.

Running "git-describe:build" (git-describe) task
>> v2.0.0-756-c03cc14

Running "jshint:beforeconcat" (jshint) task
>> 47 files lint free.

Running "concat:js" (concat) task

Running "concat:css" (concat) task

Running "cssmin:minify" (cssmin) task
>> 1 file created. 134.03 kB → 103.95 kB

Running "copy:main" (copy) task
Created 74 directories, copied 195 files

Done, without errors.


[17:41:23] 'buildMirador' errored after 29 s
[17:41:23] Error: task completion callback called too many times
    at finish (/vagrant/app/node_modules/orchestrator/lib/runTask.js:15:10)
    at cb (/vagrant/app/node_modules/orchestrator/lib/runTask.js:29:3)
    at /vagrant/app/gulpfile.js:107:7
    at ChildProcess.exithandler (child_process.js:635:7)
    at ChildProcess.EventEmitter.emit (events.js:98:17)
    at maybeClose (child_process.js:743:16)
    at Process.ChildProcess._handle.onexit (child_process.js:810:5)
```

This is related to pull requests #98 #99 which resolved issue #96. The problem with building mirador from source is that we now have to debug mirador build issues in the context of this project. I'm wondering if this gulp task would be better utilized as an aid to development rather than a requirement to building and deploying the media manager. Mirador itself, although used in our project, is really a separate library and project and should be treated as such. The rate of change in mirador is likely to be much different than rate of change in the media manager and I think it would be best to decouple the two. Having said that, it will still be useful to be able to quickly build the latest version of mirador inside the media manager project itself, so the gulp task will be a useful development tool.

I would propose the following process to replace building Mirador from scratch every time we need to deploy somewhere (including locally):

1) Build the latest version of mirador in our fork of the official repository (pull upstream changes first):  https://github.com/Harvard-ATG/mirador.
2) Tag release and upload build files as ZIP.
3) Copy the build files into the media manager vendor directory:  `app/src/vendor/mirador`
4) Commit the changes 
5) Repeat 1-4 as necessary.

Note that sometimes it might not be necessary to build & release in our fork if the official Mirador project has a release available that we can use. The process above is useful if the Mirador project has made significant progress on their master branch and we want to be able to use it in the media manager, but they haven't deemed it ready yet for wide distribution and therefore have not made an official release available.

**Comment by arthurian** [comment]
Fixed by #109
